### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by Sunshine168** [capricorncd/image-process-tools#10]
这边把这个嵌入React组件中使用了，有打算支持一下ssr吗， 目前看来document 和 window对象有直接暴露的情况。

**Comment by capricorncd** [comment]
你在引入`image-process`之前，加入`ssr-window`试试：
```
import { window, document } from 'ssr-window'
``` 
https://github.com/nolimits4web/ssr-window

**Comment by Sunshine168** [comment]
试了一下直接在项目里面引入不行，估计要在这个包里面引入才可以
