### ISSUE TITLE
image-process  2.2.3 源码在那里可下载到

### ISSUE THREAD

**Issue by wzhsh90** [capricorncd/image-process-tools#7]
你原来这个程序里面没有处理ios 拍照图片方向变化问题，我需要你的源码进行调整

**Comment by capricorncd** [comment]
https://github.com/capricorncd/zx-editor 这个里面旋转功能；用的exif.min.js

**Comment by capricorncd** [comment]
https://github.com/capricorncd/image-process-tools/tree/v2.2.4
